AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Docker Swarm set up with 1 leader and 3 followers (worker nodes)

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t3.micro
      - t2.micro
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.

  MyIP:
    Description: Your IP address in CIDR format (e.g. 203.0.113.1/32).
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access via my IP address
      SecurityGroupIngress:
        - IpProtocol: '-1'
          CidrIp: !Ref MyIP

  master:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05576a079321f21f8
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: 'master'
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Master Node!</h1></body></html>" > /var/www/html/index.html

          sudo yum install -y docker
          sudo systemctl enable docker.service
          sudo systemctl start docker.service
          sudo docker swarm init
          sudo chown -R $USER:$USER /var/www/html/
          sudo echo $(docker swarm join-token worker -q) > /var/www/html/worker-join-token

  worker1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05576a079321f21f8
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: 'worker1'
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl start httpd
              systemctl enable httpd
              echo "<html><body><h1>Worker Node 1!</h1></body></html>" > /var/www/html/index.html

              sudo yum install -y docker
              sudo systemctl enable docker.service
              sudo systemctl start docker.service

              sudo docker swarm join --token $(curl http://${MasterIp}/worker-join-token) ${MasterIp}:2377
            - MasterIp: !GetAtt master.PrivateIp
    DependsOn:
      - master
  worker2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05576a079321f21f8
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: 'worker2'
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl start httpd
              systemctl enable httpd
              echo "<html><body><h1>Worker Node 2!</h1></body></html>" > /var/www/html/index.html

              sudo yum install -y docker
              sudo systemctl enable docker.service
              sudo systemctl start docker.service

              sudo docker swarm join --token $(curl http://${MasterIp}/worker-join-token) ${MasterIp}:2377
            - MasterIp: !GetAtt master.PrivateIp
    DependsOn:
      - master

  worker3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05576a079321f21f8
      InstanceType: !Ref InstanceType
      Tags:
        - Key: 'Name'
          Value: 'worker3'
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              yum update -y
              yum install -y httpd
              systemctl start httpd
              systemctl enable httpd
              echo "<html><body><h1>Worker Node 3!</h1></body></html>" > /var/www/html/index.html

              sudo yum install -y docker
              sudo systemctl enable docker.service
              sudo systemctl start docker.service

              sudo docker swarm join --token $(curl http://${MasterIp}/worker-join-token) ${MasterIp}:2377
            - MasterIp: !GetAtt master.PrivateIp
    DependsOn:
      - master
Outputs:
  MasterURL:
    Value: !Join
      - ''
      - - http://
        - !GetAtt master.PublicDnsName
    Description: Website URL
  Woker1URL:
    Value: !Join
      - ''
      - - http://
        - !GetAtt worker1.PublicDnsName
    Description: Website URL
  Woker2URL:
    Value: !Join
      - ''
      - - http://
        - !GetAtt worker2.PublicDnsName
    Description: Website URL
  Woker3URL:
    Value: !Join
      - ''
      - - http://
        - !GetAtt worker3.PublicDnsName
    Description: Website URL
